site:
  name: Lavandina
  site: 'https://lavandina.pe'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M  # Asumiendo que mantienes la misma ID de verificación

# Default SEO metadata
metadata:
  title:
    default: Lavandina - Lavandería Personalizada en Miraflores
    template: '%s — Lavandina'
  description: "Lavandina ofrece un servicio de lavandería personalizado en Miraflores, Perú, destacando por la atención detallada a cada prenda y cliente."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Lavandina
    images:
      - url: '~/assets/images/default.png'  # Cambiar a una imagen más representativa de Lavandina
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@lavandina_pe'  # Cambiar al handle de Twitter apropiado si está disponible
    site: '@lavandina_pe'
    cardType: summary_large_image

i18n:
  language: en  # Cambiar a español
  textDirection: ltr

apps:
  blog:
    isEnabled: false  # Deshabilitar si no se utilizará un blog

analytics:
  vendors:
    googleAnalytics:
      id: null # or 'G-XXXXXXXXXX'  # Añadir el ID de Google Analytics si está disponible

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
